### ISSUE TITLE
Consider ENES HPC TF metrics: should these be included in performance?

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-cim-v2-schema#13]
Might be an optional set of questions ... or a profile, or what. Anyway, these are they:

Metric | Description
-- | --
Model | Model name and version
CMIP6 Config | Descriptive tag of CMIP6 experiment
Platform | Machine used
Total Simulated Years | Total number of years simulated for the CMIP6 experiment
Data Produced Size | Total data outputs produced by the CMIP6 experiment (Total disk space required for all data saved from CMIP6 runs)
Total core hours | Total number of core hours used by the CMIP6 experiment
Pflops-hour peak and linpack | Equivalent Peak and Linpack PFlop-hours. For a given computer used look up the total number of cores (N), the total peak performance (RPeak) and the Linpack Performance (Rmax) in the Top 500 list (http://www.top500.org/list). Equivalent Peak and Linpack performance are then given by C*Rpeak/N and C*Rmax/N respectively where C is the number of core hours given (total core hours) by the experiment.

**Comment by bnlawrence** [comment]
Clearly some of them need to discriminate between the number recorded in the CMIP6 archive, and the number carried out. However, these are really not performance metrics, but rather experiment "support metrics". Need to think about how best to handle those.

**Comment by davidhassell** [comment]
As you have said (partially or wholly) elsewhere, Bryan ...

_Pflops-hour_, _peak_ and _linpack_ could be added to **compute_pool** (https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/master/platform_classes.py#L39).

_Model_, _CMIP6 config_, _platform_ are already in the CIM.

I'm not sure what to do about the others to do with aggregated amounts across all simulations in an experiment. Perhaps the **Ensemble** (https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/master/activity_classes.py#L119) could have some "resources" properties added to it to capture them?

If we can get all of these into the CIM, compiling this entire table from the ES-DOC will be trivial.

**Comment by bnlawrence** [comment]
I've added a new class in platform: ``project_cost'' which addresses some of these things, but not the linkpack, pflop stuff ... which belongs in machine. It's yuck. I'll add it there.
