### ISSUE TITLE
Establish version numbering within the CIM itself

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-cim-v2-schema#14]
Changes to the CIM have not been following the Contributing guidelines. We need to get an initial change to the CIM itself, so that we can stack up pull requests appropriately.

**Comment by davidhassell** [comment]
This change is "trivial" in the major.minor.trivial versioning scheme

**Comment by bnlawrence** [comment]
This was fixed in a recent merge.
