### ISSUE TITLE
Proposed CIM2 changes resulting from November face-to-face

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-cim-v2-schema#2]
During the face-to-face in November 2016 some structural changes to the CIM were discussed.

The general focus of these changes was to delegate more responsibility to the specializations, following the principle that the utility of the CIM lies in the genericity of the schema and the customizability of the specializations.

These changes are currently described at https://docs.google.com/document/d/1xaTWPilOtRCzNysficzB_SAeDOyu4fvLRpDu2s9ZLjo/edit

Please review, and on Monday 9th December 2016 I shall copy the text from the google doc to this issue, which will then be the place to discuss and change these ideas.

**Comment by allynt** [comment]
Another summary of changes can be seen by comparing the files in https://github.com/ES-DOC/esdoc-cim/tree/master/v2/schema-science-proposal

**Comment by allynt** [comment]
These changes have been approved.
