### ISSUE TITLE
use of the same class name in multiple packages

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-cim-v2-schema#20]
We have got `axis_member` in both activity and designing. 
Is that by design, or error? 

Do we have a policy on using the same class name in different packages? In principle packages are used in part to support exactly this functionality, but we could choose either to explicitly allow it or to explicitly forbid it. We should do one or the other for clarity.

**Comment by davidhassell** [comment]
Resolved by deleting the place-holder copy. See Pull Request #22
