### ISSUE TITLE
topics, topic_properties, and topic_property sets have mandatory specialisation id

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-cim-v2-schema#27]
This can't be mandatory, otherwise the CIM can only be used with a specialisation, and that makes it only for use with CMIP ... very bad for sustainability.

**Comment by bnlawrence** [comment]
@momipsl Any objection to making this not mandatory as a short term solution? I think there may be other places where we need to consider "CMIPisms" that have crept into the core CIM, but we can control this one now?

**Comment by bnlawrence** [comment]
[Mark is ok with making cardinality 0.1 for specialisation id](https://es-doc.slack.com/archives/C0LCK0NQ3/p1563558505006100)

**Comment by bnlawrence** [comment]
Long term solution is simply to leave these inside a completely revised topic structure as a CMIP specialisation. A candidate for this could go straight into a revised CIM2.x.

**Comment by davidhassell** [comment]
Sounds good to me.

**Comment by bnlawrence** [comment]
Fixed in 2.2
