### ISSUE TITLE
Make sure all appropriate classes have a label defined for them.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-cim-v2-schema#3]
WHO: @allynt

Make sure (at least) all document-level classes have a label defined for them.

The CIM Schema has the concept of a "label".  This is defined by adding the following structure to the schema definition:

`        'pstr': ('lorem {} ipsum {}', ('a', 'b',)),`

where the first argument is a format string, and the second argument is a list of fields names whose values should be used to fill in the `{}` sections in the string.

There is code in pyesdoc to record these labels.  And there is code in the QConfig Generator to do clever things with those labels.

However, not all classes in the CIM have defined a label.  It is particularly important that document-level classes like "science.Realm" have these defined so that the Questionnaire knows how to display a list of realm documents.  The CIM should therefore be updated.

**Comment by allynt** [comment]
**list of proposed class labels:**  (the ones I've changed - both explicitly and by virtue of inheriting one I've changed - are marked in bold)

activity_classes.py:
- **activity**:  'pstr': ('{}', ('canonical_name',)), 
  - this is newly added for this ticket
- axis_member: _None_
- **conformance**: _inherits activity's label_
- conformance_type: _None_
- **ensemble**: _inherits activity's label_
- ensemble_axis: 'pstr': ('{}', ('axis',)),
  - this makes no sense; there is no "axis" property
- **ensemble_member**: 'pstr': ('{}', ('simulation',)),
  - this is newly added for this ticket
- **parent_simulation**: 'pstr': ('{}', ('parent',)),
  - this is newly added for this ticket
- **uber_ensemble**: _inherits ensemble's label_

data_classes.py:
- data_association_types: _None_
- **dataset**: 'pstr': ('{}', ('name',)),
  - this is newly added for this ticket
- input_dataset: _None_
- **downscaling**: _inherits simulation's label_
- **simulation**: _inherits activity's label_
- variable_collection: _None_

designing_classes.py:
- axis_member():
  - this is repeated from activity_classes.py; not sure what it's doing here
-  **domain_requirements**(): _inherits numerical_requirement's label_
-  **ensemble_requirement**(): _inherits numerical_requirement's label_
-  **forcing_constraint**(): _inherits numerical_requirement's label_
-  **initialisation_requirement**():_inherits numerical_requirement's label_
-  **multi_ensemble**(): _inherits numerical_requirement's label_
-  **numerical_experiment**(): _inherits activity's label_
-  **numerical_requirement**(): _inherits activity's label_ 
-  **output_requirement**(): _inherits numerical_requirement's label_
-  **project**(): _inherits activity's label_
-  **simulation_plan**(): _inherits activity's label_
-  **start_date_ensemble**(): _inherits numerical_requirement's label_
-  **temporal_constraint**(): _inherits numerical_requirement's label_

platform_classes.py:
- **component_performance**(): _inherits performance's label_
  - changed for this ticket
- **compute_pool**(): 'pstr': ('{}'), ('name',)),
  - newly added for this ticket
- **machine**(): _inherits partition's label_
- **partition**():  'pstr': ('{})', ('name',)),
  - newly added for this ticket
- **performance**():  'pstr': ('{} (sypd:{})', ('name', 'simulated_years_per_day')),
  - changed for this ticket
- **storage_pool**(): 'pstr': ('{}'), ('name',)),
  - newly added for this ticket
- storage_volume(): 'pstr': ('{} {}', ('volume', 'units')),

science_classes.py:
- **model**(): _inherits component_base's label_
- **realm**(): 'pstr': ('{}', ('canonical_name')),        
  - newly added for this ticket
- **topic**(): 'pstr': ('{}', ('short_name')),        
  - newly added for this ticket
- **topic_property_set**(): 'pstr': ('{}', ('specialization_id')),        
  - newly added for this ticket
- **topic_property**(): 'pstr': ('{}: {}', ('specialization_id', 'values')),        
  - newly added for this ticket

shared_classes.py:
- text_blob():'pstr': ('{}', ('content',)),
  - this seems like a bad idea for a label
- **citation**(): 'pstr': ('{}', ('title',)),
  - newly added for this ticket
- extra_attribute(): 'pstr': ('{}:{}', ('key', 'value')),
- **online_resource**(): 'pstr': ('{}', ('linkage',)),
  - newly added for this ticket
- **party**():'pstr': ('{}', ('name',)),
  - newly added for this ticket
- **quality_review**(): 'pstr': ('{}: {}', ('target_document', 'quality_status',)),
  - newly added for this ticket
- responsibility(): 'pstr': ('{}:{}', ('role', 'parties')),

shared_classes_doc.py:
- **doc_reference**(): 'pstr': ('{}', ('canonical_name',)),
  - newly added for this ticket

software_classes.py:
- **component_base**(): 'pstr': ('{}', ('name',)),
  - newly added for this ticket
- **implementation**():  'pstr': ('{}', ('name',)),
  - newly added for this ticket
- composition(): _None_
- development_path(): _None_
- entry_point(): _None_
- gridspec(): _None_
- software_component(): _None_
- variable(): _None_

time.py:
- calendar(): 'pstr': ('{}', ('standard_name',)),
- date_time():'pstr': ('{}(offset {})', ('value', 'offset')),
- datetime_set(): _None_
- irregular_dateset(): _inherits datetime_set's label_
- regular_timeset(): 'pstr': ('{} times from {} at {} intervals', ('length', 'start_date', 'increment')),
- time_period(): 'pstr': ('{} {}', ('length', 'units')),

**Comment by bnlawrence** [comment]
Does the last comment mean that they don't survive into pyesdoc instances?   That's somewhat regardless of whether or not they appear in the CIM ...  so we should do this before release of a "paper version".

**Comment by bnlawrence** [comment]
There are some interesting assumptions in this ticket, primarily that pstr is inherited by sub-classes, which I don't think would fit for my understanding of our metamodel.

My expectation is that only _properties_ (and maybe _members_ for enums, but I'm not sure we have any internal enumeration sub-classes) are inherited by sub-classes ... which would mean `pstr` cannot appear on any abstract class (and  it does on some).

**Comment by bnlawrence** [comment]
So apparently this was done, so the ticket ought to be closed. So I will, but I'll generate a new ticket which refers back to this one on the metamodel issue.
