### ISSUE TITLE
Data Package - Too many CMIPisms

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-cim-v2-schema#35]
1. The data package holds the simulation, which includes a number of attributes which are really CMIP attributes (forcing index et al). It might be cleaner to put a CMIP subclass of simulation into this work package.
1. `input_dataset` is really just a "manually modified dataset", but the use as an input is a concept which belongs to whatever uses it as input, so the name is wrong.
1. `downscaling` seems to be an unnecessary specialisation, it could be hoovered up into a related_to/related by association class, unless we want to add some real downscaling attributes (method etc).

**Comment by davidhassell** [comment]
I agree,

**Comment by bnlawrence** [comment]
Done. New CMIP package.
