### ISSUE TITLE
parent_simulation class poorly named and positioned

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-cim-v2-schema#37]
The `parent_simulation` class has attributes which suggested it was a child simulation, and the  simulation attribute is also poorly named and defined. Attached is a view of the UML after moving the simulation into the activity package, but before dealing with this:
[doc_activity.pdf](https://github.com/ES-DOC/esdoc-cim-v2-schema/files/3445818/doc_activity.pdf)

**Comment by davidhassell** [comment]
I agree.
