### ISSUE TITLE
Code auto-formatting with 'black' for consistency

### ISSUE THREAD

**Issue by sadielbartholomew** [ES-DOC/esdoc-cim-v2-schema#47]
I am keen to blast the codebase with 'black' to auto-format the Python modules in a consistent way, in particular because it will convert the CIM classes code to be less dense and therefore more readable. For example, if I run the command `black --line-length 79 platform_classes.py` to auto-format that file, the classes becomes easier to digest as demonstrated with the `machine` class which becomes:

```python
def machine():
    """A computer/system/platform/machine which is used for simulation."""
    return {
        "type": "class",
        "base": "platform.partition",
        "is_abstract": False,
        "pstr": ("{}", ("name",)),
        "is_document": True,
        "properties": [
            (
                "peak_performance",
                "shared.numeric",
                "0.1",
                "Total peak performance (RPeak in Top500 lingo)",
            ),
            (
                "linpack_performance",
                "shared.numeric",
                "0.1",
                "Linpack performance (RMax in Top500 lingo)",
            ),
        ],
    }
```
whereas at present it is hard to pick out the cardinality, etc.:

https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/0b065120cce05ad30a84c8868059512e3f396a2f/platform_classes.py#L92-L108

**Comment by davidhassell** [comment]
I'm all for code linting using `black` and `flake8`, and friends.
