### ISSUE TITLE
Extension to fix storage of the performance of sub-components 

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-cim-v2-schema#48]
The current CIM v2.2 `Performance` class is broken, in that the performance of a sub-component cannot be stored because the sub-component's performance description is another Performance instance, which in turn can only describe the performance of a `Model`, rather than the required `Realm`:

```python
def performance():  # CIM v2.2
    """
    Describes the properties of a performance of a configured model on
    a particular system/machine.
    Based on "CPMIP: Measurements of Real Computational Performance of
    Earth System Models" (Balaji et. al. 2016, doi:10.5194/gmd-2016-197).
    """
    return {
        'type': 'class',
        'base': None,
        'is_abstract': False,
        'pstr': ('{} (sypd:{})', ('name', 'simulated_years_per_day')),
        'is_document': True,
        'properties': [
            ('name', 'str', '0.1',
                "Name for performance (experiment/test/whatever)."),

            # CPMIP model and platform
            ('model', 'linked_to(science.model)', '1.1',
                "Model for which performance was tested."),
# <snip>

            # Subcomponent performance
            ('subcomponent_performance', 'linked_to(platform.performance)', '0.N',
                "Describes the performance of each subcomponent.")
        ]
    }
```
A proposed solution to this is to allow the `Type` of a property to be a collection of types, any one of which is acceptable:

```python
            # CPMIP model/realm and platform
            ("model",
             "linked_to(science.model), linked_to(science.realm)",
             "1.1",
             "Model for which performance was tested."),
```
This is readable to humans, easily parsed, and  is clear to software, especially the validator.

Another proposal was to modify the "linked_to" syntax to allow the possibility of a "part" of the Type to be defined instead of the type itself. Something like (alert - made-up syntax!) "linked_to(science.model[:realm])". This approach is, I feel, not as clean as the approach described above because a) it's less readable and harder to parse; and b) it necessarily defines a _property_ of the Type, rather than explicitly another type, and so is harder to validate and doesn't explicitly state what the alternative type actually is.

Thoughts welcome.

**Comment by sadielbartholomew** [comment]
Thanks for the excellent summary of matters discussed with various relevant parties in the email thread, @davidhassell.

I very much like the sound of the proposed solution and think it is much superior to the alternative you have also outlined, for the reasons you give. Both of the solutions covered would do the job and seem to be backwards compatible, though, which are the two considerations for a solution that would be acceptable to me. So if there is strong opinion towards the alternative that would be okay by me. Otherwise, the proposed one sounds ideal and let's go with that!

**Comment by davidhassell** [comment]
Thanks, @sadielbartholomew. I should hasten to add that I worked on this with @momipsl, and most of the good ideas are his. Mark is currently investigating the pyesdoc implications.

**Comment by davidhassell** [comment]
Hi - given the impending release of Performance document collection to the CMIP6 community, it'd be good to get this issue resolved. To start things off I shall create a PR with the aforementioned CIM changes.  @momipsl, has there been any progress with the pyesdoc side of things? Getting the CIM right is the top priority for Spreadsheet creation, but we won't (I think) be able to create archived docs until pyesdoc has been extended. 

Many thanks.
