### ISSUE TITLE
Should a description for a `conformance` class be compulsory?

### ISSUE THREAD

**Issue by sadielbartholomew** [ES-DOC/esdoc-cim-v2-schema#52]
For the `conformance` activity class, there is a description property which is currently set to be **compulsory**:

https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/1ba7e90a43a00a878c501d5b8e880b30bf6d80a7/activity_classes.py#L179

In discussion with @davidhassell, we agreed we think it should instead be **optional** (i.e. `0.1` cardinality) because when the appropriate value for "conformance_achieved" (an [`activity.conformance_type`](https://github.com/ES-DOC/esdoc-cim-v2-schema/blob/1ba7e90a43a00a878c501d5b8e880b30bf6d80a7/activity_classes.py#L184-L203)) is "Conformed", it will often be the case that this value alone is sufficient, with nothing to say by way of further description (some further description may be desirable in some cases for a simulation marked as conforming to the requirements, and should be included always for any other conformance value e.g. "Not Conformed", but certainly it is superfluous for at least some cases).

@bnlawrence what do you think?

**Comment by davidhassell** [comment]
Thanks, Sadie - looks good to me.

**Comment by bnlawrence** [comment]
I think the cardinality went to 1 when we removed a controlled vocab which would have said something like "conformed in model code ... conformed by dataset ... conformed by parameter" ... and it should be compulsory for partial conformance. Meanwhile, I agree, the simplest is to make it 0.1 for now.

**Comment by sadielbartholomew** [comment]
Thanks @bnlawrence for the context and for sharing your opinion. And thanks also @davidhassell for your confirmation that I captured our thinking correctly.

Unless anyone has a final objection, I will quickly check that @greensladem is happy and if so, go ahead and make the change, then.

**Comment by davidhassell** [comment]
Great. Thanks, Sadie and Bryan.
