### ISSUE TITLE
The citation class needs machine-parseable properties

### ISSUE THREAD

**Issue by davidhassell** [ES-DOC/esdoc-cim-v2-schema#6]
The existing string-valued properties are not parseable … there is no standard way they have been created, so they cannot be used in a publication without a massive manual step.

Three additional properties are proposed (`bibtex`, `year`, and `authors`) which provide a breakdown of the existing properties.

**Comment by bnlawrence** [comment]
If this is approved, I'd be happy to work with the existing citations to get them parsed ab initio into these new properties.

**Comment by davidhassell** [comment]
Just to note that we need this PR to create documents from the existing  citations spreadsheets

**Comment by bnlawrence** [comment]
This was done at some point
